project_id = "qydcfiufcoztzymedtbo"

[functions.copilotkit]
verify_jwt = false  # CopilotKit handles its own auth

[functions.stripe-webhook]
verify_jwt = false  # Stripe signature provides authentication

[functions.model-casting-agent]
verify_jwt = true  # Requires authenticated users

[functions.runway-timing-agent]
verify_jwt = true  # Requires authenticated users

[functions.health]
verify_jwt = false  # Public health endpoint for monitoring

[functions.vendor-coordinator-agent]
verify_jwt = true  # Requires authenticated users

[functions.event-health-scorer]
verify_jwt = true  # Requires authenticated users
