// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:locale?/:shopid/orders/:token/authenticate": {
    params: {
      "locale"?: string;
      "shopid": string;
      "token": string;
    };
  };
  "/:locale?/blogs/:blogHandle/:articleHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/:locale?/collections/:collectionHandle": {
    params: {
      "locale"?: string;
      "collectionHandle": string;
    };
  };
  "/:locale?/api/:version/graphql.json": {
    params: {
      "locale"?: string;
      "version": string;
    };
  };
  "/:locale?/api/review/:productHandle": {
    params: {
      "locale"?: string;
      "productHandle": string;
    };
  };
  "/:locale?/sitemap/:type/:page.xml": {
    params: {
      "locale"?: string;
      "type": string;
      "page": string;
    };
  };
  "/:locale?/blogs/:blogHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
    };
  };
  "/:locale?/products/:productHandle": {
    params: {
      "locale"?: string;
      "productHandle": string;
    };
  };
  "/:locale?/policies/:policyHandle": {
    params: {
      "locale"?: string;
      "policyHandle": string;
    };
  };
  "/:locale?/api/predictive-search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/authorize": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/featured-items": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/pages/:pageHandle": {
    params: {
      "locale"?: string;
      "pageHandle": string;
    };
  };
  "/:locale?/account/logout": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/products": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/login": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/discount/:code": {
    params: {
      "locale"?: string;
      "code": string;
    };
  };
  "/:locale?/sitemap.xml": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/countries": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/customer": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/products": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/klaviyo": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/product": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/address/:id": {
    params: {
      "locale"?: string;
      "id": string;
    };
  };
  "/:locale?/account/orders/:id": {
    params: {
      "locale"?: string;
      "id": string;
    };
  };
  "/:locale?/account/addresses": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/profile": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/edit": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart/add/:variantId": {
    params: {
      "locale"?: string;
      "variantId": string;
    };
  };
  "/:locale?/cart/:lines": {
    params: {
      "locale"?: string;
      "lines": string;
    };
  };
  "/robots.txt": {
    params: {};
  };
  "/:locale?/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:locale?/:shopid/orders/:token/authenticate" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/collections/:collectionHandle" | "/:locale?/api/:version/graphql.json" | "/:locale?/api/review/:productHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/products/:productHandle" | "/:locale?/policies/:policyHandle" | "/:locale?/api/predictive-search" | "/:locale?/account/authorize" | "/:locale?/api/featured-items" | "/:locale?/collections" | "/:locale?/pages/:pageHandle" | "/:locale?/account/logout" | "/:locale?/policies" | "/:locale?/products" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/sitemap.xml" | "/:locale?/api/countries" | "/:locale?/api/customer" | "/:locale?/api/products" | "/:locale?/api/klaviyo" | "/:locale?/api/product" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/address/:id" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/edit" | "/:locale?/account/*" | "/:locale?" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/add/:variantId" | "/:locale?/cart/:lines" | "/robots.txt" | "/:locale?/*" | "/graphiql" | "/subrequest-profiler";
  };
  "routes/($locale).$shopid.orders.$token.authenticate.tsx": {
    id: "routes/($locale).$shopid.orders.$token.authenticate";
    page: "/:locale?/:shopid/orders/:token/authenticate";
  };
  "routes/($locale).blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/($locale).blogs.$blogHandle.$articleHandle";
    page: "/:locale?/blogs/:blogHandle/:articleHandle";
  };
  "routes/($locale).collections.$collectionHandle.tsx": {
    id: "routes/($locale).collections.$collectionHandle";
    page: "/:locale?/collections/:collectionHandle";
  };
  "routes/($locale).api.$version.[graphql.json].tsx": {
    id: "routes/($locale).api.$version.[graphql.json]";
    page: "/:locale?/api/:version/graphql.json";
  };
  "routes/($locale).api.review.$productHandle.ts": {
    id: "routes/($locale).api.review.$productHandle";
    page: "/:locale?/api/review/:productHandle";
  };
  "routes/($locale).sitemap.$type.$page[.xml].tsx": {
    id: "routes/($locale).sitemap.$type.$page[.xml]";
    page: "/:locale?/sitemap/:type/:page.xml";
  };
  "routes/($locale).blogs.$blogHandle._index.tsx": {
    id: "routes/($locale).blogs.$blogHandle._index";
    page: "/:locale?/blogs/:blogHandle";
  };
  "routes/($locale).products.$productHandle.tsx": {
    id: "routes/($locale).products.$productHandle";
    page: "/:locale?/products/:productHandle";
  };
  "routes/($locale).policies.$policyHandle.tsx": {
    id: "routes/($locale).policies.$policyHandle";
    page: "/:locale?/policies/:policyHandle";
  };
  "routes/($locale).api.predictive-search.ts": {
    id: "routes/($locale).api.predictive-search";
    page: "/:locale?/api/predictive-search";
  };
  "routes/($locale).account_.authorize.ts": {
    id: "routes/($locale).account_.authorize";
    page: "/:locale?/account/authorize";
  };
  "routes/($locale).api.featured-items.ts": {
    id: "routes/($locale).api.featured-items";
    page: "/:locale?/api/featured-items";
  };
  "routes/($locale).collections._index.tsx": {
    id: "routes/($locale).collections._index";
    page: "/:locale?/collections";
  };
  "routes/($locale).pages.$pageHandle.tsx": {
    id: "routes/($locale).pages.$pageHandle";
    page: "/:locale?/pages/:pageHandle";
  };
  "routes/($locale).account_.logout.ts": {
    id: "routes/($locale).account_.logout";
    page: "/:locale?/account/logout";
  };
  "routes/($locale).policies._index.tsx": {
    id: "routes/($locale).policies._index";
    page: "/:locale?/policies";
  };
  "routes/($locale).products._index.tsx": {
    id: "routes/($locale).products._index";
    page: "/:locale?/products";
  };
  "routes/($locale).account_.login.tsx": {
    id: "routes/($locale).account_.login";
    page: "/:locale?/account/login";
  };
  "routes/($locale).discount.$code.tsx": {
    id: "routes/($locale).discount.$code";
    page: "/:locale?/discount/:code";
  };
  "routes/($locale).[sitemap.xml].tsx": {
    id: "routes/($locale).[sitemap.xml]";
    page: "/:locale?/sitemap.xml";
  };
  "routes/($locale).api.countries.ts": {
    id: "routes/($locale).api.countries";
    page: "/:locale?/api/countries";
  };
  "routes/($locale).api.customer.ts": {
    id: "routes/($locale).api.customer";
    page: "/:locale?/api/customer";
  };
  "routes/($locale).api.products.ts": {
    id: "routes/($locale).api.products";
    page: "/:locale?/api/products";
  };
  "routes/($locale).api.klaviyo.ts": {
    id: "routes/($locale).api.klaviyo";
    page: "/:locale?/api/klaviyo";
  };
  "routes/($locale).api.product.ts": {
    id: "routes/($locale).api.product";
    page: "/:locale?/api/product";
  };
  "routes/($locale).account.tsx": {
    id: "routes/($locale).account";
    page: "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/address/:id" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/edit" | "/:locale?/account/*";
  };
  "routes/($locale).account.orders._index.tsx": {
    id: "routes/($locale).account.orders._index";
    page: "/:locale?/account/orders";
  };
  "routes/($locale).account.address.$id.tsx": {
    id: "routes/($locale).account.address.$id";
    page: "/:locale?/account/address/:id";
  };
  "routes/($locale).account.orders.$id.tsx": {
    id: "routes/($locale).account.orders.$id";
    page: "/:locale?/account/orders/:id";
  };
  "routes/($locale).account.addresses.tsx": {
    id: "routes/($locale).account.addresses";
    page: "/:locale?/account/addresses";
  };
  "routes/($locale).account.profile.tsx": {
    id: "routes/($locale).account.profile";
    page: "/:locale?/account/profile";
  };
  "routes/($locale).account.edit.tsx": {
    id: "routes/($locale).account.edit";
    page: "/:locale?/account/edit";
  };
  "routes/($locale).account.$.tsx": {
    id: "routes/($locale).account.$";
    page: "/:locale?/account/*";
  };
  "routes/($locale)._index.tsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).search.tsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale).cart.tsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart" | "/:locale?/cart/add/:variantId" | "/:locale?/cart/:lines";
  };
  "routes/($locale).cart.add.$variantId.ts": {
    id: "routes/($locale).cart.add.$variantId";
    page: "/:locale?/cart/add/:variantId";
  };
  "routes/($locale).cart.$lines.tsx": {
    id: "routes/($locale).cart.$lines";
    page: "/:locale?/cart/:lines";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/($locale).$.tsx": {
    id: "routes/($locale).$";
    page: "/:locale?/*";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/home/sk/amo/secreto-jardin-storefront/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};